---
dependency:
  enabled: false
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: buster
    box: debian/buster64
    interfaces:
      - network_name: private_network
        auto_config: true
        ip: 172.16.100.12
        type: static
lint: |
  set -e
  yamllint .
  ansible-lint --exclude roles/ --exclude molecule/ --exclude library/
  flake8 --exclude roles,molecule,library
provisioner:
  name: ansible
  playbooks:
    converge: ../../full.yml
  options:
    become: true
    extra-vars:
      ansible_sudo: true
      ansible_become_pass: vagrant
      unprivileged_user: molecule
      ssh_pub_key: ~/.ssh/id_rsa.pub
      dropbear:
        ssh_pub_key: ~/.ssh/id_rsa.pub
        static_ip: 172.16.100.12
        gateway: 10.0.2.2
        netmask: 255.255.255.0
        hostname: buster
        network_interface: eth1
scenario:
  name: default
verifier:
  name: testinfra
  options:
    sudo: true
